/* SafetyAssure — functional browser demo + Supabase-ready SaaS shell */
const C=window.SAFETYASSURE_CONFIG||{};
const SAAS=!!(C.supabaseUrl&&C.supabasePublishableKey&&window.supabase);
const sb=SAAS?window.supabase.createClient(C.supabaseUrl,C.supabasePublishableKey):null;
const KEY="safetyassure_demo_v1";
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random());
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const statusLabel=s=>({NEW:"New",DATA_ENTRY:"Data Entry",MEDICAL_REVIEW:"Medical Review",QC_REVIEW:"QC Review",READY_FOR_DISTRIBUTION:"Ready for Distribution",DISTRIBUTED:"Distributed",FOLLOW_UP:"Follow-up",CLOSED:"Closed"}[s]||s);
const statusClass=s=>({NEW:"new",DATA_ENTRY:"data",MEDICAL_REVIEW:"medical",QC_REVIEW:"qc",READY_FOR_DISTRIBUTION:"ready",DISTRIBUTED:"distributed",FOLLOW_UP:"follow",CLOSED:"closed"}[s]||"new");
const nextStates={NEW:["DATA_ENTRY"],DATA_ENTRY:["MEDICAL_REVIEW"],MEDICAL_REVIEW:["QC_REVIEW"],QC_REVIEW:["READY_FOR_DISTRIBUTION"],READY_FOR_DISTRIBUTION:["DISTRIBUTED","FOLLOW_UP"],DISTRIBUTED:["FOLLOW_UP","CLOSED"],FOLLOW_UP:["MEDICAL_REVIEW","CLOSED"],CLOSED:[]};
const seed=[
 {case_id:"CA-2026-00001",receipt_date:"2026-09-18",country:"Canada",source:"Patient",patient_age:54,patient_sex:"F",product:"Product A",event:"Headache",meddra_pt:"Headache",seriousness:"Non-serious",outcome:"Recovering",status:"DATA_ENTRY",due_date:"2026-09-25",assignee:"Case Processor",narrative:"Patient reported headache two days after treatment."},
 {case_id:"CA-2026-00002",receipt_date:"2026-09-19",country:"USA",source:"HCP",patient_age:66,patient_sex:"M",product:"Product B",event:"Rash",meddra_pt:"Rash",seriousness:"Serious",outcome:"Recovering",status:"MEDICAL_REVIEW",due_date:"2026-09-26",assignee:"Medical Reviewer",narrative:"Serious rash requiring medical assessment."},
 {case_id:"CA-2026-00003",receipt_date:"2026-09-20",country:"UK",source:"Patient Support Program",patient_age:43,patient_sex:"F",product:"Product C",event:"Nausea",meddra_pt:"Nausea",seriousness:"Non-serious",outcome:"Recovered",status:"READY_FOR_DISTRIBUTION",due_date:"2026-09-27",assignee:"PV Manager",narrative:"PSP-originated case."},
 {case_id:"CA-2026-00004",receipt_date:"2026-09-21",country:"Germany",source:"Regulatory Authority",patient_age:71,patient_sex:"M",product:"Product A",event:"Anaphylaxis",meddra_pt:"Anaphylactic reaction",seriousness:"Serious",outcome:"Recovered",status:"QC_REVIEW",due_date:"2026-09-28",assignee:"QC Reviewer",narrative:"Serious allergic reaction; medical review completed."},
 {case_id:"CA-2026-00005",receipt_date:"2026-09-22",country:"France",source:"HCP",patient_age:38,patient_sex:"F",product:"Product D",event:"Fatigue",meddra_pt:"Fatigue",seriousness:"Non-serious",outcome:"Unknown",status:"NEW",due_date:"2026-09-29",assignee:"Unassigned",narrative:"Initial report received."},
 {case_id:"CA-2026-00006",receipt_date:"2026-09-23",country:"Canada",source:"Patient",patient_age:59,patient_sex:"M",product:"Product B",event:"Dizziness",meddra_pt:"Dizziness",seriousness:"Non-serious",outcome:"Recovering",status:"DISTRIBUTED",due_date:"2026-09-30",assignee:"Regulatory",narrative:"Distributed to applicable authority."}
];
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{cases:seed,events:seed.map(c=>({id:uid(),case_id:c.case_id,action:"CASE_CREATED",detail:"Initial demo case",actor:"Demo User",at:new Date().toISOString()})),actions:[],settings:{org:"SafetyAssure Demo Organization"}}}catch{return{cases:seed,events:[],actions:[],settings:{org:"SafetyAssure Demo Organization"}}}}
let db=load(); let page="home"; let selected=null; let search=""; let filterStatus="ALL"; let filterSerious="ALL";
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function toast(x){let e=document.createElement("div");e.className="toast";e.textContent=x;document.body.appendChild(e);setTimeout(()=>e.remove(),2400)}
function id(){return `CA-${new Date().getFullYear()}-${String(db.cases.length+1).padStart(5,"0")}`}
function addEvent(case_id,action,detail){db.events.unshift({id:uid(),case_id,action,detail,actor:"Current User",at:new Date().toISOString()})}
function transition(c,to){if(!nextStates[c.status].includes(to))return toast("That workflow transition is not permitted.");let from=c.status;c.status=to;c.updated_at=new Date().toISOString();addEvent(c.case_id,"STATUS_CHANGED",`${statusLabel(from)} → ${statusLabel(to)}`);save();toast(`Case ${c.case_id} moved to ${statusLabel(to)}`);render()}
function openCase(caseId){selected=db.cases.find(c=>c.case_id===caseId);page="case";render()}
function nav(p){page=p;selected=null;render()}
function modal(html){let m=document.createElement("div");m.className="modal";m.innerHTML=html;document.body.appendChild(m);m.addEventListener("click",e=>{if(e.target===m)m.remove()});return m}
function newCase(){
 const m=modal(`<div class="modal-card"><div class="modal-head"><b>Book In — New ICSR</b><button class="close">×</button></div>
 <form id="caseForm"><div class="modal-body"><div class="banner">Minimum ICSR validity: identifiable patient + identifiable reporter/source + suspect product + adverse event/reaction. Demo form only; do not enter real patient data.</div>
 <div class="form-grid">
 <div class="field"><label>Receipt date</label><input name="receipt_date" type="date" value="${today()}" required></div>
 <div class="field"><label>Country</label><select name="country"><option>Canada</option><option>USA</option><option>UK</option><option>Germany</option><option>France</option><option>Other</option></select></div>
 <div class="field"><label>Source</label><select name="source"><option>HCP</option><option>Patient</option><option>Patient Support Program</option><option>Regulatory Authority</option><option>Literature</option><option>Other</option></select></div>
 <div class="field"><label>Patient age</label><input name="patient_age" type="number" min="0" max="130"></div>
 <div class="field"><label>Patient sex</label><select name="patient_sex"><option>Unknown</option><option>F</option><option>M</option><option>Other</option></select></div>
 <div class="field"><label>Suspect product</label><input name="product" required placeholder="Product name"></div>
 <div class="field"><label>Event verbatim</label><input name="event" required placeholder="Reported event"></div>
 <div class="field"><label>Seriousness</label><select name="seriousness"><option>Non-serious</option><option>Serious</option></select></div>
 <div class="field"><label>Outcome</label><select name="outcome"><option>Unknown</option><option>Recovering</option><option>Recovered</option><option>Not recovered</option><option>Fatal</option></select></div>
 <div class="field"><label>Due date</label><input name="due_date" type="date"></div>
 <div class="field full"><label>Narrative</label><textarea name="narrative" placeholder="Initial narrative..."></textarea></div>
 </div></div><div class="modal-foot"><button type="button" class="btn close">Cancel</button><button class="btn primary">Create Case</button></div></form></div>`);
 m.querySelectorAll(".close").forEach(x=>x.onclick=()=>m.remove());
 m.querySelector("#caseForm").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);let c={case_id:id(),receipt_date:f.get("receipt_date"),country:f.get("country"),source:f.get("source"),patient_age:f.get("patient_age"),patient_sex:f.get("patient_sex"),product:f.get("product"),event:f.get("event"),meddra_pt:"Not yet coded",seriousness:f.get("seriousness"),outcome:f.get("outcome"),status:"NEW",due_date:f.get("due_date")||f.get("receipt_date"),assignee:"Unassigned",narrative:f.get("narrative")};db.cases.unshift(c);addEvent(c.case_id,"CASE_CREATED","Case booked in");save();m.remove();toast(`${c.case_id} created`);nav("queue")}
}
function pill(s,ser=false){return `<span class="pill ${ser?(s==="Serious"?"serious":"nserious"):statusClass(s)}">${esc(ser? s:statusLabel(s))}</span>`}
function kpi(label,val,note){return `<div class="card"><div class="kpi-label">${label}</div><div class="kpi-value">${val}</div><div class="kpi-note">${note||""}</div></div>`}
function dashboard(){
 const cs=db.cases, count=s=>cs.filter(c=>c.status===s).length, overdue=cs.filter(c=>c.due_date<today()&&!["CLOSED","DISTRIBUTED"].includes(c.status)).length;
 return `<div class="page-head"><div><h2>SafetyAssure</h2><p>Patient Safety • Governance • Compliance • Intelligence</p></div><button class="btn primary" onclick="newCase()">＋ Book In Case</button></div>
 <div class="grid kpis">${kpi("New Cases",count("NEW"),"Awaiting intake")}${kpi("In Data Entry",count("DATA_ENTRY"),"Case processing")}${kpi("Medical Review",count("MEDICAL_REVIEW"),"Clinical assessment")}${kpi("Ready for Distribution",count("READY_FOR_DISTRIBUTION"),"Submission queue")}${kpi("Overdue",overdue,"Workflow due dates")}${kpi("Total Cases",cs.length,"Current organization")}</div>
 <div class="grid two" style="margin-top:16px"><div class="card"><h3 class="section-title">Case Intake Trend</h3><div class="bars">${[3,5,4,7,6,9,8].map((v,i)=>`<div class="bar" style="height:${v*12}px"><span>${i+18}</span></div>`).join("")}</div></div>
 <div class="card"><h3 class="section-title">Case Status Overview</h3><div class="donut"></div><div class="stat-line"><span>Open workflow</span><b>${cs.filter(c=>c.status!=="CLOSED").length}</b></div><div class="stat-line"><span>Serious</span><b>${cs.filter(c=>c.seriousness==="Serious").length}</b></div></div></div>
 <div class="grid three" style="margin-top:16px"><div class="card"><h3 class="section-title">Top Products</h3>${["Product A","Product B","Product C","Product D"].map(x=>{let n=cs.filter(c=>c.product===x).length;return `<div class="stat-line"><span>${x}</span><b>${n}</b></div>`}).join("")}</div>
 <div class="card"><h3 class="section-title">Top Countries</h3>${["Canada","USA","UK","Germany","France"].map(x=>{let n=cs.filter(c=>c.country===x).length;return `<div class="stat-line"><span>${x}</span><b>${n}</b></div>`}).join("")}</div>
 <div class="card"><h3 class="section-title">Sources</h3>${["HCP","Patient","Patient Support Program","Regulatory Authority"].map(x=>{let n=cs.filter(c=>c.source===x).length;return `<div class="stat-line"><span>${x}</span><b>${n}</b></div>`}).join("")}</div></div>`;
}
function queuePage(title,statuses){
 let cs=db.cases.filter(c=>(!statuses||statuses.includes(c.status))&&(!search||JSON.stringify(c).toLowerCase().includes(search.toLowerCase()))&&(filterStatus==="ALL"||c.status===filterStatus)&&(filterSerious==="ALL"||c.seriousness===filterSerious));
 return `<div class="page-head"><div><h2>${title}</h2><p>${cs.length} case(s) in the current view.</p></div><div><button class="btn primary" onclick="newCase()">＋ Book In</button></div></div>
 <div class="card"><div style="display:flex;gap:8px;margin-bottom:14px;flex-wrap:wrap"><input id="q" placeholder="Search case, product, event, country..." value="${esc(search)}" style="flex:1;min-width:220px;padding:9px;border:1px solid #cfd9de;border-radius:8px"><select id="fs" style="padding:9px;border:1px solid #cfd9de;border-radius:8px"><option value="ALL">All statuses</option>${Object.keys(statusLabel({})).length?Object.keys(nextStates).map(s=>`<option value="${s}" ${filterStatus===s?"selected":""}>${statusLabel(s)}</option>`).join(""):""}</select><select id="fser" style="padding:9px;border:1px solid #cfd9de;border-radius:8px"><option value="ALL">All seriousness</option><option ${filterSerious==="Serious"?"selected":""}>Serious</option><option ${filterSerious==="Non-serious"?"selected":""}>Non-serious</option></select><button class="btn" onclick="exportCSV()">Export CSV</button></div>
 <div class="table-wrap"><table class="table"><thead><tr><th>Case</th><th>Receipt</th><th>Country</th><th>Source</th><th>Product</th><th>Event / PT</th><th>Seriousness</th><th>Status</th><th>Due</th><th>Action</th></tr></thead><tbody>${cs.length?cs.map(c=>`<tr><td><b>${esc(c.case_id)}</b></td><td>${esc(c.receipt_date)}</td><td>${esc(c.country)}</td><td>${esc(c.source)}</td><td>${esc(c.product)}</td><td>${esc(c.event)}<br><span class="muted">${esc(c.meddra_pt)}</span></td><td>${pill(c.seriousness,true)}</td><td>${pill(c.status)}</td><td>${esc(c.due_date)}</td><td><button class="btn small" onclick="openCase('${c.case_id}')">Open</button></td></tr>`).join(""):`<tr><td colspan="10" class="empty">No cases match the current filters.</td></tr>`}</tbody></table></div></div>`;
}
function casePage(){
 let c=selected;if(!c)return nav("queue");
 let ev=db.events.filter(e=>e.case_id===c.case_id).sort((a,b)=>b.at.localeCompare(a.at));
 let ns=nextStates[c.status]||[];
 return `<div class="page-head"><div><h2>${esc(c.case_id)}</h2><p>${esc(c.product)} · ${esc(c.event)} · ${pill(c.status)}</p></div><button class="btn" onclick="nav('queue')">← Back to Queue</button></div>
 <div class="banner warning">Development prototype: this record is stored locally in Demo Mode unless a Supabase project is configured.</div>
 <div class="grid two"><div class="card"><h3 class="section-title">Case Details</h3><div class="form-grid">
 ${["receipt_date","country","source","patient_age","patient_sex","product","event","meddra_pt","seriousness","outcome","due_date","assignee"].map(k=>`<div class="field"><label>${k.replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase())}</label><input id="edit_${k}" value="${esc(c[k])}" ${k==="case_id"?"disabled":""}></div>`).join("")}
 <div class="field full"><label>Narrative</label><textarea id="edit_narrative">${esc(c.narrative)}</textarea></div></div><div style="margin-top:14px"><button class="btn primary" onclick="saveCase('${c.case_id}')">Save Case</button></div></div>
 <div class="card"><h3 class="section-title">Workflow</h3><div class="banner">Current: <b>${statusLabel(c.status)}</b><br>Next permitted transitions are controlled by the workflow state machine.</div>${ns.length?ns.map(n=>`<button class="btn" style="margin:4px 4px 4px 0" onclick="doTransition('${c.case_id}','${n}')">Move to ${statusLabel(n)}</button>`).join(""):`<span class="muted">No further standard transition.</span>`}
 <hr style="border:0;border-top:1px solid #edf1f3;margin:18px 0"><h3 class="section-title">Audit / Workflow History</h3><div class="timeline">${ev.map(e=>`<div class="timeline-item"><strong>${esc(e.action)}</strong><div>${esc(e.detail)}</div><div>${new Date(e.at).toLocaleString()} · ${esc(e.actor)}</div></div>`).join("")}</div></div></div>`;
}
function saveCase(caseId){let c=db.cases.find(x=>x.case_id===caseId);["receipt_date","country","source","patient_age","patient_sex","product","event","meddra_pt","seriousness","outcome","due_date","assignee"].forEach(k=>c[k]=document.getElementById("edit_"+k).value);c.narrative=document.getElementById("edit_narrative").value;addEvent(caseId,"CASE_UPDATED","Case fields updated");save();toast("Case saved");render()}
function doTransition(caseId,to){let c=db.cases.find(x=>x.case_id===caseId);if(c)transition(c,to)}
function exportCSV(){let rows=db.cases.map(c=>[c.case_id,c.receipt_date,c.country,c.source,c.patient_age,c.patient_sex,c.product,c.event,c.meddra_pt,c.seriousness,c.outcome,c.status,c.due_date,c.assignee]);let csv=[["Case ID","Receipt Date","Country","Source","Age","Sex","Product","Event","MedDRA PT","Seriousness","Outcome","Status","Due Date","Assignee"],...rows].map(r=>r.map(x=>`"${String(x??"").replaceAll('"','""')}"`).join(",")).join("\\n");let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="SafetyAssure_Line_Listing.csv";a.click();URL.revokeObjectURL(a.href)}
function governance(){return `<div class="page-head"><div><h2>Governance & Compliance</h2><p>Inspection-readiness controls and operational compliance workspace.</p></div><button class="btn primary" onclick="addAction()">＋ New Action</button></div>
<div class="grid four">${kpi("Open CAPA",db.actions.filter(x=>x.type==="CAPA"&&x.status!=="Closed").length,"Tracked actions")}${kpi("Deviations",db.actions.filter(x=>x.type==="Deviation").length,"Current register")}${kpi("Change Controls",db.actions.filter(x=>x.type==="Change Control").length,"Controlled changes")}${kpi("Audit Events",db.events.length,"System activity")}</div>
<div class="grid two" style="margin-top:16px"><div class="card"><h3 class="section-title">Governance Controls</h3>${["PV SOP currency","Training completion","Case timeliness","Reconciliation","Controlled terminology","Inspection evidence"].map((x,i)=>`<div class="stat-line"><span>${x}</span><b>${i===2?"96%":i===3?"100%":"Active"}</b></div><div class="progress"><i style="width:${[96,92,96,100,100,88][i]}%"></i></div>`).join("")}</div>
<div class="card"><h3 class="section-title">Compliance Action Register</h3><div class="table-wrap"><table class="table"><thead><tr><th>Type</th><th>Title</th><th>Owner</th><th>Status</th></tr></thead><tbody>${db.actions.length?db.actions.map(a=>`<tr><td>${esc(a.type)}</td><td>${esc(a.title)}</td><td>${esc(a.owner)}</td><td>${esc(a.status)}</td></tr>`).join(""):`<tr><td colspan="4" class="empty">No actions recorded.</td></tr>`}</tbody></table></div></div></div>`}
function addAction(){let m=modal(`<div class="modal-card"><div class="modal-head"><b>New Governance Action</b><button class="close">×</button></div><form id="af"><div class="modal-body"><div class="form-grid"><div class="field"><label>Type</label><select name="type"><option>CAPA</option><option>Deviation</option><option>Change Control</option><option>Audit Finding</option></select></div><div class="field"><label>Owner</label><input name="owner" value="PV Manager"></div><div class="field full"><label>Title</label><input name="title" required placeholder="Action title"></div><div class="field full"><label>Description</label><textarea name="description"></textarea></div></div></div><div class="modal-foot"><button type="button" class="btn close">Cancel</button><button class="btn primary">Create</button></div></form></div>`);m.querySelectorAll(".close").forEach(x=>x.onclick=()=>m.remove());m.querySelector("#af").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);db.actions.unshift({id:uid(),type:f.get("type"),owner:f.get("owner"),title:f.get("title"),description:f.get("description"),status:"Open"});save();m.remove();toast("Governance action created");render()}}
function intelligence(){let serious=db.cases.filter(c=>c.seriousness==="Serious");return `<div class="page-head"><div><h2>Safety Intelligence</h2><p>Operational safety signals and review queues using current demo data.</p></div></div><div class="grid three">${kpi("Serious Cases",serious.length,"Current case set")}${kpi("Unique Products",new Set(db.cases.map(c=>c.product)).size,"Case distribution")}${kpi("Open Follow-up",db.cases.filter(c=>c.status==="FOLLOW_UP").length,"Cases requiring follow-up")}</div><div class="grid two" style="margin-top:16px"><div class="card"><h3 class="section-title">Serious Cases by Product</h3>${[...new Set(db.cases.map(c=>c.product))].map(p=>{let n=serious.filter(c=>c.product===p).length;return `<div class="stat-line"><span>${p}</span><b>${n}</b></div>`}).join("")}</div><div class="card"><h3 class="section-title">Signal Review Queue</h3><div class="banner warning">This is decision-support only. No automated signal conclusion is produced by the prototype.</div>${serious.map(c=>`<div class="list-row"><span><b>${c.case_id}</b> · ${esc(c.event)}</span><button class="btn small" onclick="openCase('${c.case_id}')">Review</button></div>`).join("")||'<div class="empty">No serious cases.</div>'}</div></div>`}
function admin(){return `<div class="page-head"><div><h2>Administration</h2><p>Organization, reference data, security and integration readiness.</p></div></div><div class="grid two"><div class="card"><h3 class="section-title">Organization</h3><div class="field"><label>Organization name</label><input value="${esc(db.settings.org)}" onchange="db.settings.org=this.value;save()"></div><p class="muted">SaaS tenancy is represented by organization membership in the Supabase schema.</p></div><div class="card"><h3 class="section-title">Security Architecture</h3>${["Authentication","Role-based access","Row-level security","Audit trail","API / Edge Functions","Backup & recovery"].map(x=>`<div class="stat-line"><span>${x}</span><b>Planned / configurable</b></div>`).join("")}</div></div><div class="grid three" style="margin-top:16px">${["Products / IDMP","MedDRA","WHODrug","E2B(R3)","SPOR / IDMP","Reporting Interfaces"].map(x=>`<div class="card"><h3 class="section-title">${x}</h3><p class="muted">Pluggable reference/integration module. Licensing, versioning and regulatory controls must be implemented before production use.</p></div>`).join("")}</div>`}
function appPage(){let navs=[["home","⌂","Home"],["book","＋","Book In"],["queue","▤","Case Management"],["medical","◉","Medical Review"],["qc","✓","QC Review"],["dist","⇧","Distribution"],["mis","▥","MIS & Line Listings"],["gov","⚑","Governance & Compliance"],["intel","◈","Safety Intelligence"],["admin","⚙","Administration"]];return `<div class="shell"><aside class="sidebar"><div class="brand"><h1>SafetyAssure</h1><p>Patient Safety • Governance • Compliance • Intelligence</p></div><nav class="nav">${navs.map(n=>`<button class="${page===n[0]?"active":""}" onclick="nav('${n[0]}')"><span>${n[1]}</span>${n[2]}</button>`).join("")}</nav><div class="sidebar-footer">SafetyAssure development environment<br>Not validated for production PV use</div></aside><main class="main"><header class="topbar"><div class="crumb">${navs.find(n=>n[0]===page)?.[2]||"SafetyAssure"}</div><div class="top-actions"><span class="mode">${SAAS?"SAAS CONNECTED":"DEMO MODE"}</span><span class="muted">${esc(db.settings.org)}</span></div></header><section class="content">${content()}</section></main></div>`}
function content(){switch(page){case"home":return dashboard();case"book":return `<div class="page-head"><div><h2>Book In</h2><p>Create and validate the minimum data needed to establish an ICSR.</p></div><button class="btn primary" onclick="newCase()">＋ New ICSR</button></div><div class="card"><div class="banner">Demo environment only. For production, connect this workflow to a validated backend, authenticated users, controlled terminology and privacy/security controls.</div><h3 class="section-title">ICSR Validity Gate</h3><div class="grid four">${["Identifiable patient","Identifiable reporter/source","Suspect product","Adverse event/reaction"].map(x=>`<div class="card"><b>✓</b><div style="margin-top:7px;font-size:12px">${x}</div></div>`).join("")}</div></div>`;case"queue":return queuePage("Case Management");case"medical":return queuePage("Medical Review",["MEDICAL_REVIEW"]);case"qc":return queuePage("QC Review",["QC_REVIEW"]);case"dist":return queuePage("Distribution",["READY_FOR_DISTRIBUTION"]);case"mis":return queuePage("MIS & Line Listings");case"gov":return governance();case"intel":return intelligence();case"admin":return admin();case"case":return casePage();default:return dashboard()}}
function render(){document.getElementById("app").innerHTML=appPage();if(page==="queue"||["medical","qc","dist","mis"].includes(page)){let q=document.getElementById("q");if(q){q.oninput=e=>{search=e.target.value;render()};q.onkeydown=e=>{if(e.key==="Enter")render()}}let fs=document.getElementById("fs");if(fs)fs.onchange=e=>{filterStatus=e.target.value;render()};let fser=document.getElementById("fser");if(fser)fser.onchange=e=>{filterSerious=e.target.value;render()}}}
render();
window.nav=nav;window.newCase=newCase;window.openCase=openCase;window.saveCase=saveCase;window.doTransition=doTransition;window.exportCSV=exportCSV;window.addAction=addAction;
